{
 "title": "Sentiment Analysis Project",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sentiment Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sentimentBucket\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r._measurement == \"sentiment_data\" and r._field == \"sentiment\")\r\n  |> map(fn: (r) => ({ r with sentiment: r._value, dummy: 1 }))\r\n  |> group(columns: [\"sentiment\"])\r\n  |> sum(column: \"dummy\")\r\n  |> map(fn: (r) => ({ _time: now(), _value: r.dummy, sentiment: r.sentiment }))\r\n"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sentimentBucket\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r._measurement == \"sentiment_data\")\n  |> filter(fn: (r) => r._field == \"sentiment\")\n  |> map(fn: (r) => ({\n        Score: if r._value == \"Very Positive\" then 2 \n               else if r._value == \"Positive\" then 1 \n               else if r._value == \"Neutral\" then 0 \n               else if r._value == \"Negative\" then -1 \n               else -2,  // Very Negative = -2\n        Time: r._time\n    }))\n  |> mean(column: \"Score\")"
    }
   ]
  },
  {
   "title": "Phrases and Sentiment",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sentimentBucket\")\n|> range(start: -24h)\n|> filter(fn: (r) => r._measurement == \"sentiment_data\")\n|> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\n|> rename(columns: { \"text\": \"Text\", \"language\": \"Language\", \"sentiment\": \"Sentiment\", \"_time\": \"Time\" })\n|> keep(columns: [\"Text\", \"Language\", \"Sentiment\", \"Time\"])\n|> sort(columns: [\"Time\"], desc: true)\n|> map(fn: (r) => ({ Text: r.Text, Language: r.Language, Sentiment: r.Sentiment, Time: string(v: r.Time) }))"
    }
   ]
  }
 ]
}